### ISSUE TITLE
Add django-secure related options

### ISSUE THREAD

**Issue by rm--** [transcode-de/cookiecutter-django-project#17]
---
- Bitbucket: https://bitbucket.org/transcode/transcode-django-project/issue/17
- Originally reported by: Markus Zapke-Gründemann
- Originally created at: 2015-02-06T21:35:34.163

**Comment by rm--** [comment]
Since `Django 1.8` [some security options](https://docs.djangoproject.com/en/1.8/ref/middleware/#django.middleware.security.SecurityMiddleware) from `django-secure` is part of the core, I think it is sufficient to enable some of them.

I suggest:
- `SECURE_CONTENT_TYPE_NOSNIFF = True` because of the last paragraph in the explanation
- `SECURE_BROWSER_XSS_FILTER = True` if when prevent XSS

I am not sure about `SECURE_HSTS_SECONDS`, `SECURE_REDIRECT_EXEMPT`,
`SECURE_SSL_HOST` and `SECURE_SSL_REDIRECT`. I think it depends of our server setup.

**Comment by keimlink** [comment]
As you already proposed we can use the security options build into Django 1.8. django-secure also suggest this in its [ latest documentation](https://django-secure.readthedocs.org/en/latest/):

> This project was merged into Django 1.8. It does not provide any additional checks beyond those included in Django 1.8+, so there is no reason to use it with Django 1.8+.

Some of the security settings have been added in 14ee203.

I think the SSL-related settings should go into a new class `SSL` that can be combined with the classes used for production sites that use SSL. Maybe a stage site does not use SSL but the production site does.
