### ISSUE TITLE
Test the project

### ISSUE THREAD

**Issue by rm--** [transcode-de/cookiecutter-django-project#18]
Test the project created by cookiecutter. We could use [Cram](https://bitheap.org/cram/) to test it.

---
- Bitbucket: https://bitbucket.org/transcode/transcode-django-project/issue/18
- Originally reported by: Markus Zapke-Gründemann
- Originally created at: 2015-02-13T02:18:55.800

**Comment by rm--** [comment]
_From Markus Zapke-Gründemann on 2015-02-19 02:36:39+00:00_

issue #15 seems to deal with the same topic.

**Comment by rm--** [comment]
_From Rene Muhl on 2015-02-26 15:43:21+00:00_

Issue #15 was marked as a duplicate of this issue.

**Comment by keimlink** [comment]
Resolved by pull request #42.
