### ISSUE TITLE
Replace Make with invoke

### ISSUE THREAD

**Issue by rm--** [transcode-de/cookiecutter-django-project#19]
`Make` could be replaced with [invoke](http://www.pyinvoke.org/). invoke is more flexible and could easier solve problems like #8.

---
- Bitbucket: https://bitbucket.org/transcode/transcode-django-project/issue/19
- Originally reported by: Markus Zapke-Gründemann
- Originally created at: 2015-02-13T02:21:04.632

**Comment by keimlink** [comment]
Maybe [rituals](https://github.com/jhermann/rituals) (Common tasks for ‘Invoke’) could be useful?

**Comment by rm--** [comment]
[corresponding invoke issue](https://github.com/pyinvoke/invoke/issues/257)

**Comment by rm--** [comment]
_Status update_:
Python 3.5.0
ivoke==0.11.1
Commands like `invoke` and `invoke -l`still ends in the known error.

**Comment by rm--** [comment]
Up to [commit](https://github.com/transcode-de/cookiecutter-django-project/commit/bb10c471ff85569d0dbf7a7c9b902a7ff9e65f40) some feature are missing:

~~\* handling of `--force True` in the following tasks `clean_backup`, `db.drop` and `db.drop_user`~~
- possible replacement of `print` in `django.startapp` for stdout in invoke
- general customization of tasks parameter

PS. `google styled napoleon docstring` of sphinx seems not necessary because e.g. `inv -h django.manage` looks very good and provides enough information like the task related options including types

**Comment by rm--** [comment]
I created a package named [jinn](https://github.com/transcode-de/jinn/) to handle python/django tasks. This issue will closed in favor of jinn.
