### ISSUE TITLE
Add pg-activity

### ISSUE THREAD

**Issue by rm--** [transcode-de/cookiecutter-django-project#3]
We should add [pg-activity](https://github.com/julmon/pg_activity) to the development packages.

---
- Bitbucket: https://bitbucket.org/transcode/transcode-django-project/issue/3
- Originally reported by: Markus Zapke-Gründemann
- Originally created at: 2014-06-18T11:42:46.973

**Comment by rm--** [comment]
_From Rene Muhl on 2014-07-23 14:08:55+00:00_

Added factory_boy and pg_activity to README

resolves issue #3
resolves issue #4

→ <<cset a341399f1dee>>

**Comment by rm--** [comment]
_From Markus Zapke-Gründemann on 2014-07-24 22:21:11+00:00_

Because [issue #13](https://github.com/julmon/pg_activity/issues/13) has been fixed but not released yet `pg_activity` can't be installed inside a virtualenv. Please test before you add new packages. We have to wait until the next release of `pg_activity` before we can add it.

**Comment by rm--** [comment]
_From Max Brauer on 2015-01-05 12:51:35+00:00_

Issue 13 was closed but nothing happend. An other user opened also a [issue](https://github.com/julmon/pg_activity/issues/34) for this problem. I asked in the Issue again if there will be a release, soon.

**Comment by rm--** [comment]
There is a [commit](https://github.com/julmon/pg_activity/commit/2ae517c3d6cb2aa615447451c36bb0ac79bbeedd) which fixes the problem. And with latest version from PYPI the error dosen't occurs anymore.

**Comment by keimlink** [comment]
Great news, so it seems ok to add it to the development requirements now.
