### ISSUE TITLE
Tox env check-manifest fails with error

### ISSUE THREAD

**Issue by rm--** [transcode-de/cookiecutter-django-project#31]
The error messages are: 
`my-project/.tox/manifest/bin/python3.4', 'setup.py', 'sdist', '-d', '/tmp/check-manifest-qkaca9_y-sdist'] failed (status 2)`
`my-project/.tox/manifest/bin/python3.4: can't open file 'setup.py': [Errno 2] No such file or directory
`

**Comment by rm--** [comment]
I don't have this error anymore, can you someone else confirm this problem?

**Comment by DebVortex** [comment]
Fine here, too. Going to close this Issue now. Tox got fixed.
