### ISSUE TITLE
Add django-template-debug

### ISSUE THREAD

**Issue by keimlink** [transcode-de/cookiecutter-django-project#55]
Add [django-template-debug](https://github.com/calebsmith/django-template-debug) for debugging and introspecting templates.

**Comment by rm--** [comment]
Are you sure?
To [setup](https://github.com/calebsmith/django-template-debug#setup) it is required to set `TEMPLATE_DEBUG`.

But after [Django docs](https://docs.djangoproject.com/en/1.8/ref/settings/#template-debug): 

```
TEMPLATE_DEBUG

Default: False
Deprecated since version 1.8:
Set the 'debug' option in the OPTIONS of a DjangoTemplates backend instead.
```

So I would avoid to add `TEMPLATE_DBUG` to our settings.

**Comment by keimlink** [comment]
Right, please use the appropriate setting for Django 1.8. Use a django-configurations value so that it can be easily changed using an environment variable.
