### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by rm--** [transcode-de/cookiecutter-django-project#6]
The documentation isn't up to date.

Since Django 1.7  the `createsuperuser` management command needs to be used to create a superuser. Older versions of Django did this automatically when calling `syncdb`.

---
- Bitbucket: https://bitbucket.org/transcode/transcode-django-project/issue/6
- Originally reported by: Rene Muhl
- Originally created at: 2014-09-09T09:36:13.504

**Comment by rm--** [comment]
_From Max Brauer on 2014-11-26 09:46:05+00:00_

Added a `make` command to create a superuser and updated the documentation.

**Comment by rm--** [comment]
_From Max Brauer on 2014-11-26 10:08:17+00:00_

Reopened the Issue. I'm going to remove the command again and solve it with Issue #8

**Comment by rm--** [comment]
We should update the documentation after #19 to prevent update documentation twice.

**Comment by keimlink** [comment]
Fixed by e480a52.
